export const FETCHING_DATA = "FETCHING_DATA";
export const FETCHING_DATA_SUCCESS = "FETCHING_DATA_SUCCESS";
export const FETCHING_DATA_ERROR = "FETCHING_DATA_ERROR";
export const CURRENT_VERSION = 1;
export const MAX_MEMORY_LENGTH = 300;