export const FETCHING_DATA = "FETCHING_DATA";
export const FETCHING_DATA_SUCCESS = "FETCHING_DATA_SUCCESS";
export const FETCHING_DATA_ERROR = "FETCHING_DATA_ERROR";

export const FETCHING_MEMORIES = "FETCHING_MEMORIES";
export const FETCHING_MEMORIES_SUCCESS = "FETCHING_MEMORIES_SUCCESS";
export const FETCHING_MEMORIES_ERROR = "FETCHING_MEMORIES_ERROR";

export const FETCHING_USER = "FETCHING_USER";
export const FETCHING_USER_SUCCESS = "FETCHING_USER_SUCCESS";
export const FETCHING_USER_ERROR = "FETCHING_USER_ERROR";

export const CURRENT_VERSION = 0;
export const MAX_MEMORY_LENGTH = 300;